#!/usr/bin/env bash
# a script that creates redirection using sed
sudo apt update
sudo apt install -y nginx

echo "Hello World!" | sudo tee /var/www/html/index.html

var_string="server_name _;\\n\\trewrite ^\\/redirect_me https:\\/\\/google.com permanent;"
sudo sed -i "s/server_name _;/$var_string/" /etc/nginx/sites-enabled/default
var_string="listen 80 default_server;\\n\
\terror_page 404 \\/404.html;\\n\
\tlocation = \\/404.html {\\n\
\t\\troot \\/var\\/www\\/html;\\n\
\t\\tinternal;\\n\
\t}"
sudo sed -i "s/listen 80 default_server;/$var_string/" /etc/nginx/sites-enabled/default
sudo service nginx restart
