#!/usr/bin/env bash
# configure nginx server to listen on port 80

# remove default nginx config
rm /etc/nginx/site-enabled/default

# config nginx to listen on port 80
ln -s /etc/nginx/site-available/default /etc/nginx/site-enabled/default
# restart nginx
service nginx restart
