#!/usr/bin/env bash
# Use pgrep to find the process ID (PID) of 7-highlander
process_id=$(pgrep -o -f "7-highlander")
if [ -n "$process_id" ]; then
    kill -15 "$process_id"
else
    echo "Process 7-highlander not found."
fi
