#!/usr/bin/env bash
#a script that loops through and print best sch
count=0
while [ $count -lt 10 ]; do
        if [ $count -eq 3 ]; then
                echo "bad luck"
        elif [ $count -eq 7 ]; then
		echo "good luck"
	else
                echo "Best School"
        fi
        ((count++))
done
