#!/usr/bin/env bash
#Initialize hour and minute variables
hour=0
minute=1
while [ $hour -le 23 ]; do
    echo "Hour: $hour"
    while [ $minute -le 59 ]; do
        echo $minute
        ((minute++))
    done
    minute=1
    ((hour++))
done
